### ISSUE TITLE
TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by jJit0** [FreeLanguageTools/vocabsieve#22]
Hi,

Since I upgrade vocabsieve to 0.8.0, I can't launch it
Here is what I got:

`pipx upgrade vocabsieve`
```
Traceback (most recent call last):
  File "/usr/local/bin/vocabsieve", line 5, in <module>
    from vocabsieve.__main__ import main
  File "/usr/local/lib/venvs/vocabsieve/lib/python3.10/site-packages/vocabsieve/__main__.py", line 1, in <module>
    from . import main
  File "/usr/local/lib/venvs/vocabsieve/lib/python3.10/site-packages/vocabsieve/main.py", line 33, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

`pipx inject vocabsieve packaging`
```
~/.local/share/FreeLanguageTools/VocabSieve
Traceback (most recent call last):
  File "/usr/local/lib/venvs/vocabsieve/bin/vocabsieve", line 8, in <module>
    sys.exit(main())
TypeError: 'module' object is not callable
```

**Comment by 1over137** [comment]
sorry, I messed up the module structure a bit initially.
Use 0.8.1

**Comment by jJit0** [comment]
Thanks, it works great with latest version
