### ISSUE TITLE
No package metadata

### ISSUE THREAD

**Issue by yaoberh** [FreeLanguageTools/vocabsieve#8]
Getting this error in Arch linux:

```
❯ python3 vocabsieve.py
Traceback (most recent call last):
  File "/home/yaoberh/vocabsieve/vocabsieve.py", line 2, in <module>
    import vocabsieve.main
  File "/home/yaoberh/vocabsieve/vocabsieve/__init__.py", line 2, in <module>
    __version__ = importlib.metadata.version('vocabsieve')
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 984, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for vocabsieve
``
```

**Comment by 1over137** [comment]
Did you first run `pip install .` in the directory?

**Comment by yaoberh** [comment]
Oh! No, I didn't. Working splendidly now :D

**Comment by 1over137** [comment]
> Oh! No, I didn't. Working splendidly now :D

Note that installing the package also installs a desktop icon and a CLI script to your path, so you can run them from anywhere.
I recommend deleting it before installing the actual release.

**Comment by Samsonasumu** [comment]
![Screenshot from 2023-06-08 02-56-04](https://github.com/FreeLanguageTools/vocabsieve/assets/99386103/2478340b-4364-47fb-be12-237cab57a781)

Help i cannt install django on ubuntu 22.04 jammy fish
